# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: helpcli
    binary: 'help'
    # Binary file name -> brews.install.bin.install: 'help'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: helpcli
    homepage: 'https://github.com/heechankim/helpcli'
    license: 'mit'
    description: 'The helpcli tool helps developers work efficiently in the terminal.'
    folder: Formula
    repository:
      owner: 'heechankim'
      name: 'homebrew-helpcli'
    install: |
      bin.install "help"
winget:
  - name: helpcli
    homepage: 'https://github.com/heechankim/helpcli'
    license: 'mit'
    short_description: 'The helpcli tool helps developers work efficiently in the terminal.'
    publisher: 'heechankim'
    package_identifier: 'heechankim.helpcli'
    url_template: "https://github.com/heechankim/helpcli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: 'heechankim'
      name: 'winget-pkgs-helpcli'


# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
