# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Help < Formula
  desc ""
  homepage "https://github.com/heechankim/helpcli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.1/helpcli_Darwin_arm64.tar.gz"
      sha256 "f79fd3892a6477902f36ccea5ac6733fcf46c3523ac7dcb6fe0662946fd8e934"

      def install
        bin.install "helpcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.1/helpcli_Darwin_x86_64.tar.gz"
      sha256 "819305365e5df07ac09a9923baaf81eed697b39c9e8579c45b08c3c2b14d66a6"

      def install
        bin.install "helpcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.1/helpcli_Linux_x86_64.tar.gz"
      sha256 "2482f62769bca42433482018b8ade2142c78dd3202f6d86d03ff9d2567460def"

      def install
        bin.install "helpcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.1/helpcli_Linux_arm64.tar.gz"
      sha256 "bcdc4a2f30c6f7265f4255946e73692dae2ccd7a181c55d48448616d11a27482"

      def install
        bin.install "helpcli"
      end
    end
  end
end
