# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Help < Formula
  desc "Release Test"
  homepage "https://github.com/heechankim/homebrew-helpcli"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.4/helpcli_Darwin_arm64.tar.gz"
      sha256 "98fde80187470b444614fe2e6cbe54f32d8e2ccf172dbff88da4741b0335a2cc"

      def install
        bin.install "helpcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.4/helpcli_Darwin_x86_64.tar.gz"
      sha256 "9a4f90ddc9f222218155d64779e11fda89ebd4dc9d638cb7c2e8c6e9808d4588"

      def install
        bin.install "helpcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.4/helpcli_Linux_x86_64.tar.gz"
      sha256 "2f8e4aab1c1170e8241c11a3f7e2e8b056c72a48dbf2d1ed536dfb993e43e1e6"

      def install
        bin.install "helpcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heechankim/helpcli/releases/download/v0.0.4/helpcli_Linux_arm64.tar.gz"
      sha256 "15e1dd12767e30bc18cabe17df5e87aa1c7b8bd7f6171384294d2b81d72d6d7d"

      def install
        bin.install "helpcli"
      end
    end
  end
end
